# http://wiki.ros.org/amcl?distro=hydro for parameters

base_frame_id: base_link
global_frame_id: map

# Publish scans from best pose at a max of 10 Hz
gui_publish_rate: 10.0

laser_max_beams: 30
laser_min_range: -1.0
laser_max_range: -1.0
laser_lambda_short: 0.1
laser_z_hit: 0.50
laser_z_rand: 0.50
laser_z_short: 0.05
laser_z_max: 0.05
laser_sigma_hit: 0.2
laser_model_type: likelihood_field
laser_likelihood_max_dist: 2.0

min_particles: 500
max_particles: 5000

kld_err: 0.05
kld_z: 0.99

odom_frame_id: odom
odom_model_type: diff
odom_alpha1: 0.2
odom_alpha2: 0.2
# translation std dev, m
odom_alpha3: 0.8
odom_alpha4: 0.2

update_min_d: 0.2
update_min_a: 0.5

resample_interval: 1

transform_tolerance: 0.1
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1