#---standard pioneer footprint---
#---(in inches)---
#footprint: [ [10, -2], [7, -2], [7, -7], [-7.5, -7], [-10, 0], [-7.5, 7], [7, 7], [7, 2], [10, 2] ]
#---(in meters)---
footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]

robot_base_frame: base_link

obstacle_layer:
   observation_sources: front_laser
   front_laser: 
      data_type: LaserScan
      topic: scan_front
      marking: true
      clearing: true
      expected_update_rate: 0.60
   obstacle_range: 2.5
   raytrace_range: 3.0
   enabled: true

inflation_layer:
   inflation_radius: 0.50
   cost_scaling_factor: 10.0
   enabled: true

footprint_layer:
   enabled: true

sonar_layer:
   enabled: true