TrajectoryPlannerROS:
   max_vel_x: 0.80
   min_vel_y: 0.10
   max_vel_theta: 0.3
   min_vel_theta: -0.3
   min_in_place_vel_theta: 0.3

   escape_vel: -0.2
   
   acc_lim_theta: 3.2
   acc_lim_x: 2.5
   acc_lim_y: 2.5

   holonomic_robot: false

   sim_time: 2.0
   dwa: true

   pdist_scale: 0.6
   gdist_scale: 0.6
   occdist_scale: 0.01

   xy_goal_tolerance: 0.10
   yaw_goal_tolerance: 0.05

   meter_scoring: true