global_frame: odom
update_frequency: 5.0
publish_frequency: 10.0
rolling_window: true
width: 5.0
height: 5.0
resolution: 0.025
static_map: false

plugins:
#   - name: sonar_layer
#     type: "sonar_layer::SonarLayer"
   - name: obstacle_layer
     type: "costmap_2d::ObstacleLayer"
#causing navigation to crash
#   - name: footprint_layer
#     type: "costmap_2d::FootprintLayer"
   - name: inflation_layer
     type: "costmap_2d::InflationLayer"
