base_global_planner: navfn/NavfnROS
#recovery_behaviors:  [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
planner_patience: 5.0

#base_local_planner: dwa_local_planner/DWAPlannerROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
controller_frequency: 5.0
